---
title: "Mais exemplos com regressão"
author: "Nazareno Andrade"
output: 
  html_notebook:
    theme: readable
    fig_width: 7
    toc: true
    toc_float: true
---


```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidymodels)
theme_set(theme_bw())
```

```{r}
cand_raw = read_csv(here::here("data/candidaturas-dep-federal-2018.csv"), 
                    col_types = "ccdcciicd")

cand = cand_raw %>% 
    mutate(branco = cor_raca == "BRANCA") %>% 
    filter(total_receita > 100, qtde_votos > 10, patrimonio > 1000, !is.na(branco)) 

glimpse(cand)
```


```{r}
cand %>% 
    ggplot(aes(x = patrimonio / 1e6, y = qtde_votos / 1e3)) + 
    geom_point(color = "dodgerblue", size = .8, alpha = .8) + 
    scale_x_log10() +
    scale_y_log10()

cand %>% 
    ggplot(aes(x = total_receita / 1e6, y = qtde_votos / 1e3)) + 
    geom_point(color = "darkorange", size = .8, alpha = .8) + 
    scale_x_log10() + 
    scale_y_log10()

cand %>% 
    ggplot(aes(x = branco, y = qtde_votos)) + 
    geom_boxplot(coef = 1000) + 
    scale_y_log10()

cand %>% 
    ggplot(aes(x = sexo, y = qtde_votos)) + 
    geom_boxplot(coef = 1000) + 
    scale_y_log10()
```

## Modelo mínimo

```{r}
m1 = lm(log10(qtde_votos) ~ log10(total_receita), data = cand)

tidy(m1, conf.int = T)
glance(m1)
```
log10(votos) = 1.25 + .53 * log10(total_receita)
votos = (10**1.25) * total_receita **.53
votos = 17.8 * total_receita **.53

```{r}
para_vis = data_grid(
    cand,
    total_receita = seq_range(total_receita, 50)
)

m1 %>% 
    augment(newdata = para_vis) %>% 
    ggplot(aes(x = total_receita, y = 10**.fitted)) + 
    geom_point() + 
    geom_line()
```

## Modelo com mais preditores

```{r}
m2 = lm(
    log10(qtde_votos) ~ log2(total_receita) + log2(patrimonio) + branco + sexo + idade,
    data = cand
)

tidy(m2, conf.int = T) 
glance(m2)

```
```{r}
para_vis = data_grid(
    cand,
    total_receita = median(total_receita), 
    # patrimonio = seq_range(patrimonio, 100),
    patrimonio = median(patrimonio),
    branco = c(TRUE, FALSE), 
    sexo = c("MASCULINO", "FEMININO"), 
    idade = seq_range(idade, 100),
    # idade = median(idade)
)

m2 %>% 
    augment(newdata = para_vis) %>% 
    # ggplot(aes(x = patrimonio / 1e6, y = 10**.fitted, color = sexo)) + 
    ggplot(aes(x = idade, y = 10**.fitted, color = sexo)) + 
    facet_wrap(~ branco) + 
    geom_line()
```


## Muitos modelos

```{r}
modelos = cand %>% 
    group_by(uf) %>% 
    nest() %>% 
    mutate(modelo = map(data, ~ lm(log10(qtde_votos) ~ log10(total_receita), data = .)), 
           coeficientes = map(modelo, tidy, conf.int = T), 
           ajuste = map(modelo, glance), 
           previsoes = map2(modelo, data, augment)) 

coeficientes = modelos %>% 
    unnest(coeficientes) %>% 
    select(-modelo, -ajuste, -data) %>% 
    filter(term != "(Intercept)")

ajustes = modelos %>% 
    unnest(ajuste) %>% 
    select(-modelo, -coeficientes, -data) 
```

```{r}
coeficientes %>% 
    ggplot(aes(x = reorder(uf, estimate), y = estimate, ymin = conf.low, ymax = conf.high)) + 
    geom_point() + 
    geom_linerange() + 
    coord_flip() 
```

```{r}
previsto = modelos %>% 
    unnest(previsoes) %>% 
    select(-modelo, -coeficientes, -data)

previsto %>% 
    ggplot(aes(x = total_receita)) + 
    facet_wrap(~ uf) + 
    geom_point(aes(y = qtde_votos), alpha = .25, color = "coral") + 
    geom_line(aes(y = 10**.fitted)) + 
    scale_y_log10() + 
    scale_x_log10()
```
